Meu_Blog/Blog/urls.py
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from .views import home, sobre, post, fortag

app_name = 'Blog'

urlpatterns = [
    path('', home, name= 'home'),
    path('sobre/', sobre),
    path('post/<int:pk>/', post, name = 'post'),
    path('tag/<slug:slug>/', fortag, name='fortag'),
    path('/ckeditor/', include('ckeditor_uploader.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Meu_Blog/Meu_Blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Blog.urls', namespace='Blog')),
    re_path('/ckeditor/', include('ckeditor_uploader.urls')),
]

Meu_Blog/Blog/models.py
from taggit.managers import TaggableManager

from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

from django.contrib.auth.models import User
from django.db import models

class Article(models.Model):
    
    Thumbnail = models.ImageField(upload_to='thumb/')
    Title = models.CharField(max_length=255, blank=False, help_text='Nome do post')
    Created_at = models.DateField(auto_now_add=True)
    Summary = RichTextField(blank=False)
    Content = RichTextUploadingField(blank=False)
    Tag = TaggableManager()
    Author = models.ForeignKey(User, on_delete=models.PROTECT, blank=False)

    class Meta:
        verbose_name_plural = 'Posts'

    def __str__(self):
        return self.Title

Meu_Blog/Blog/views.py
from django.shortcuts import render, get_object_or_404

from .models import Article
from taggit.models import Tag

def home(request):

    posts = Article.objects.all()

    return render(request, 'home.html', {'posts': posts})

def fortag(request, slug):

    tag = get_object_or_404(Tag, slug = slug)

    posts = Article.object.filter(Tag = tag)

    context = {
        'tag' : tag,
        'posts' : posts
    }

    return render(request, 'fortag.html', context)


def post(request, pk):

    Post = get_object_or_404(Article, pk=pk)

    return render(request, 'post.html', {'Post': Post})


def sobre(request):

    return render(request, 'sobre.html')

Meu_Blog/Blog/templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="pt-BR">

<head>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.2, user-scalable=yes" />

    <title>{% block head_title %} {% endblock %}| Meu Blog</title>

    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel='stylesheet' href="{% static 'css/font-awesome.css' %}">

    <link rel="stylesheet" href="{% static 'css/tagsinput' %}">
    <link rel="stylesheet" href="{% static 'css/tags.css' %}">
    <script type='text/javascript' src="{% static 'js/jquery.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/jquery-migrate.min.js' %}"></script>

    <link rel='stylesheet' id='suevafree-minimal-layout-css' href="{% static 'css/minimal-layout.css' %}" type='text/css' media='all' />
    <link rel='stylesheet' id='suevafree-template-css' href="{% static 'css/template.css' %}" type='text/css' media='all' />
    <link rel='stylesheet' id='suevafree-woocommerce-css' href="{% static 'css/woocommerce.css' %}" type='text/css' media='all' />
    <link rel='stylesheet' id='suevafree_google_fonts-css' href="{% static 'css/font-country.css' %}" type='text/css' media='all' />
    <link rel='stylesheet' id='suevafree-header_layout_1-css' href="{% static 'css/header_layout_1.css'%}" type='text/css' media='all' />

    <meta name='robots' content='noindex,nofollow' />
    <link rel='dns-prefetch' href='//fonts.googleapis.com' />
    <link rel='dns-prefetch' href='//s.w.org' />
    <link rel="alternate" type="application/rss+xml" title="Theme Preview &raquo; Feed" href="https://wp-themes.com/suevafree/?feed=rss2" />
    <link rel="alternate" type="application/rss+xml" title="Theme Preview &raquo; Comments Feed" href="https://wp-themes.com/suevafree/?feed=comments-rss2" />
    <script type="text/javascript">
        window._wpemojiSettings = {
            "baseUrl": "https:\/\/s.w.org\/images\/core\/emoji\/12.0.0-1\/72x72\/",
            "ext": ".png",
            "svgUrl": "https:\/\/s.w.org\/images\/core\/emoji\/12.0.0-1\/svg\/",
            "svgExt": ".svg",
            "source": {
                "concatemoji": "https:\/\/wp-themes.com\/wp\/wp-includes\/js\/wp-emoji-release.min.js?ver=5.4-beta3-47400"
            }
        };
        /*! This file is auto-generated */
        ! function(e, a, t) {
            var r, n, o, i, p = a.createElement("canvas"),
                s = p.getContext && p.getContext("2d");

            function c(e, t) {
                var a = String.fromCharCode;
                s.clearRect(0, 0, p.width, p.height), s.fillText(a.apply(this, e), 0, 0);
                var r = p.toDataURL();
                return s.clearRect(0, 0, p.width, p.height), s.fillText(a.apply(this, t), 0, 0), r === p.toDataURL()
            }

            function l(e) {
                if (!s || !s.fillText) return !1;
                switch (s.textBaseline = "top", s.font = "600 32px Arial", e) {
                    case "flag":
                        return !c([127987, 65039, 8205, 9895, 65039], [127987, 65039, 8203, 9895, 65039]) && (!c([55356, 56826, 55356, 56819], [55356, 56826, 8203, 55356, 56819]) && !c([55356, 57332, 56128, 56423, 56128, 56418, 56128, 56421, 56128, 56430, 56128, 56423, 56128, 56447], [55356, 57332, 8203, 56128, 56423, 8203, 56128, 56418, 8203, 56128, 56421, 8203, 56128, 56430, 8203, 56128, 56423, 8203, 56128, 56447]));
                    case "emoji":
                        return !c([55357, 56424, 55356, 57342, 8205, 55358, 56605, 8205, 55357, 56424, 55356, 57340], [55357, 56424, 55356, 57342, 8203, 55358, 56605, 8203, 55357, 56424, 55356, 57340])
                }
                return !1
            }

            function d(e) {
                var t = a.createElement("script");
                t.src = e, t.defer = t.type = "text/javascript", a.getElementsByTagName("head")[0].appendChild(t)
            }
            for (i = Array("flag", "emoji"), t.supports = {
                    everything: !0,
                    everythingExceptFlag: !0
                }, o = 0; o < i.length; o++) t.supports[i[o]] = l(i[o]), t.supports.everything = t.supports.everything && t.supports[i[o]], "flag" !== i[o] && (t.supports.everythingExceptFlag = t.supports.everythingExceptFlag && t.supports[i[o]]);
            t.supports.everythingExceptFlag = t.supports.everythingExceptFlag && !t.supports.flag, t.DOMReady = !1, t.readyCallback = function() {
                t.DOMReady = !0
            }, t.supports.everything || (n = function() {
                t.readyCallback()
            }, a.addEventListener ? (a.addEventListener("DOMContentLoaded", n, !1), e.addEventListener("load", n, !1)) : (e.attachEvent("onload", n), a.attachEvent("onreadystatechange", function() {
                "complete" === a.readyState && t.readyCallback()
            })), (r = t.source || {}).concatemoji ? d(r.concatemoji) : r.wpemoji && r.twemoji && (d(r.twemoji), d(r.wpemoji)))
        }(window, document, window._wpemojiSettings);
    </script>
    <style type="text/css">
        img.wp-smiley,
        img.emoji {
            display: inline !important;
            border: none !important;
            box-shadow: none !important;
            height: 1em !important;
            width: 1em !important;
            margin: 0 .07em !important;
            vertical-align: -0.1em !important;
            background: none !important;
            padding: 0 !important;
        }
    </style>
    <link rel='stylesheet' id='wp-block-library-css' href="{% static 'css/style.min.css'%}" type='text/css' media='all' />
    <link rel='stylesheet' id='bootstrap-css' href='https://wp-themes.com/wp-content/themes/suevafree/assets/css/bootstrap.css?ver=3.3.7' type='text/css' media='all' />
    <link rel='stylesheet' id='swipebox-css' href='https://wp-themes.com/wp-content/themes/suevafree/assets/css/swipebox.css?ver=1.3.0' type='text/css' media='all' />
    <link rel='stylesheet' id='prettyPhoto-css' href='https://wp-themes.com/wp-content/themes/suevafree/assets/css/prettyPhoto.css?ver=3.1.6' type='text/css' media='all' />

    <link rel='https://api.w.org/' href='https://wp-themes.com/suevafree/index.php?rest_route=/' />
    <link rel="EditURI" type="application/rsd+xml" title="RSD" href="https://wp-themes.com/wp/xmlrpc.php?rsd" />
    <link rel="wlwmanifest" type="application/wlwmanifest+xml" href="https://wp-themes.com/wp/wp-includes/wlwmanifest.xml" />
    <meta name="generator" content="WordPress 5.4-beta3-47400" />
    <style type="text/css">
        #header.header-5 {
            background-image: url(https://wp-themes.com/wp-content/themes/suevafree/assets/images/background/header.jpg);
            -webkit-background-size: cover !important;
            -moz-background-size: cover !important;
            -o-background-size: cover !important;
            background-size: cover !important;
            background-attachment: fixed;
        }
    </style>
</head>

<body class="home blog">

    <div id="wrapper">

        <div id="header-wrapper" class="header-1">

            <header id="header">

                <div class="container">

                    <div class="row">

                        <div class="col-md-12">

                            <div id="logo">
                                <a href="{% url 'Blog:home' %}" title='Blog_name' class='logo'>
                                    Meu Blog
                                    <span>
                                        Você foi pego em um genjutsu
                                    </span>
                                </a>
                            </div>

                            <button class="menu-toggle" aria-controls="suevafree-mainmenu" aria-expanded="false" type="button">
                                <span aria-hidden="true">Menu</span>
                                <span class="dashicons" aria-hidden="true"></span>
                            </button>

                            <nav id="suevafree-mainmenu" class="suevafree-menu suevafree-general-menu tinynav-menu">

                                <false class="default-menu">
                                    <ul>
                                        <li class="page_item page-item-2">
                                            <a href="{% url 'Blog:home' %}">Home</a>
                                        </li>

                                        <li class="page_item page-item-46 page_item_has_children">
                                            <a href="/categorias/">Categorias</a>
                                            <ul class='children'>
                                                <li class="page_item page-item-49">
                                                    <a href="#">Categoria 1</a>
                                                </li>
                                                <li class="page_item page-item-49">
                                                    <a href="#">Categoria 2</a>
                                                </li>
                                                <li class="page_item page-item-49">
                                                    <a href="#">Categoria 3</a>
                                                </li>
                                                <li class="page_item page-item-49">
                                                    <a href="#">Categoria 4</a>
                                                </li>
                                            </ul>
                                        </li>

                                        <li class="page_item page-item-2">
                                            <a href="/sobre/">Sobre</a>
                                        </li>
                                    </ul>

                                </false>

                            </nav>

                        </div>

                    </div>

                </div>

            </header>

        </div>

        {% block content %} {% endblock %}

        <footer id="footer">

            <div class="container">

                <div class="row copyright">

                    <div class="col-md-5">

                        <p>
                            Copyright Meu Blog 2020 |
                            <a href="https://www.themeinprogress.com/" target="_blank">
                                Tema de ThemeinProgress
                            </a> | Criado por:
                            <a href="https://instagram.com/santos_natanoficial/" rel="generator">
                                Natan Santos
                            </a>
                        </p>

                    </div>

                </div>

            </div>

        </footer>


    </div>

    <div id="back-to-top" class="back-to-top"><i class="fa fa-chevron-up"></i></div>
    <script type='text/javascript' src="{% static 'js/jquery.easing.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/jquery.nicescroll.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/jquery.swipebox.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/jquery.scrollTo.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/prettyPhoto.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/tinynav.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/tipsy.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/touchSwipe.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/imagesloaded.min.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/masonry.min.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/template.js' %}"></script>
    <script type='text/javascript'>
        /* <![CDATA[ */
        var accessibleNavigationScreenReaderText = {
            "expandMain": "Open the main menu",
            "collapseMain": "Close the main menu",
            "expandChild": "expand submenu",
            "collapseChild": "collapse submenu"
        };
        /* ]]> */
    </script>
    <script type='text/javascript' src="{% static 'js/navigation.js' %}"></script>
    <script type='text/javascript' src="{% static 'js/wp-embed.min.js' %}"></script>

    <script src="{% static 'js/tagsinput.js' %}"></script>

</body>

</html>

Meu_Blog/Blog/templates/fortag.html
{% extends 'base.html' %}{% block head_title %} {{ tag }} {% endblock %} {% block content %}

<div id="content" class="container">

    <div class="row">
        <div class="post-container col-md-12">

            <article class="post-article category">

                <h1>Tag: {{tag}}</h1>

            </article>

        </div>

    </div>
    <div class="row masonry" id="masonry" style="position: relative; height: 880px;">

        {% for post in posts %}

        <div class="post-container masonry-item col-md-4">

            <div class="post-article post-details post-details-1  ">

                <h3 class="title">
                    <a href="{% url 'Blog:post' pk=post.pk %}">{{post.Title}}</a>
                </h3>
                <div class="line">

                    <div class="entry-info">

                        <span><i class="fa fa-clock-o" aria-hidden="true"></i>{{post.Created_at}}</span>

                    </div>

                </div>

                <p>{{post.Summary|safe}}
                    <a class="read-more " href="{% url 'Blog:post' pk=post.pk %}" title="Read More">
                        <span class="button default">Leia Mais</span>
                    </a>
                </p>

            </div>

        </div>

        {% endfor %}


    </div>


</div>
{% endblock %}

Meu_Blog/Blog/templates/home.html
{% extends 'base.html' %}

{% block head_title %} Home {% endblock %}

{% load static %}

{% block content %}


    <div id="content" class="container masonry-container">

        <div class="row masonry" id="masonry">

            {% for post in posts %}

                <div class="post-container masonry-item col-md-4">

                    <div class="post-article post-details post-details-1  ">

                        <h3 class="title">
                            <a href="{% url 'Blog:post' pk=post.pk %}">{{post.Title}}</a>
                        </h3>
                        <div class="line">

                            <div class="entry-info">

                                <span><i class="fa fa-clock-o" aria-hidden="true"></i>{{post.Created_at}}</span>

                            </div>

                        </div>

                        <p>{{post.Summary|safe}}
                            <a class="read-more " href="{% url 'Blog:post' pk=post.pk %}" title="Read More"> 
                                <span class="button default">Leia Mais</span>
                            </a>
                        </p>

                    </div>

                </div>

            {% endfor %}

        </div>

     </div>

{% endblock %}

Meu_Blog/Blog/templates/post.html
{% extends 'base.html' %} {% block head_title %} {{ Post.Title }} {% endblock %} {% block content %}

<div class="row">

    <div class="col-md-8 right-sidebar">

        <div class="row">

            <div class="post-container col-md-12">


                <div class="post-article post-details post-details-1  ">

                    <h1 class="title">{{Post.Title}}</h1>
                    <div class="line">

                        <div class="entry-info">

                            <span>
                                <i class="fa fa-clock-o"></i>
                                {{Post.Created_at}}
                            </span>

                        </div>

                    </div>

                    <div style="width: 565px" class="wp-caption alignnone">
                        <img class="wp-image-59" alt="Thumbnail" src="{{Post.Thumbnail.url}}" width="555" height="348">
                    </div>

                    {{Post.Content | safe }}

                    <footer class="line">
                        <span class="entry-info">
                            <i class="fa fa-tags" aria-hidden="true"></i>
                            <strong>Tags:</strong>
                            {% for tag in Post.Tag.all %}
                            <a href="{% url 'Blog:fortag' slug=tag|slugify }" class="mr-1 balde balde-info">{{ tag }}</a> 
                            {% endfor %}
                        </span> 
                        
                    </footer>
                </div>

            </div>

        </div>

    </div>


    <div id="sidebar" class="col-md-4 sidebar-area">

        <div class="post-container">

            <div class="post-article">

                <div class="widget-box widget_calendar">
                    <h4 class="title">Calendário</h4>
                    <div id="calendar_wrap" class="calendar_wrap">
                        <SCRIPT LANGUAGE="JavaScript">
                            var day_of_week = new Array('D', 'S', 'T', 'Q', 'Q', 'S', 'S');
                            var month_of_year = new Array('Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro');

                            var Calendar = new Date();

                            var year = Calendar.getYear(); // Retorna o ano
                            var month = Calendar.getMonth(); // Retorna mes (0-11)
                            var today = Calendar.getDate(); // Retorna dias (1-31)
                            var weekday = Calendar.getDay(); // Retorna dias (1-31)

                            var DAYS_OF_WEEK = 7; // "constant" para o numero de dias na semana
                            var DAYS_OF_MONTH = 31; // "constant" para o numero de dias no mes
                            var cal; // Usado para imprimir na tela

                            Calendar.setDate(1); // Comecar o calendario no dia '1'
                            Calendar.setMonth(month); // Comecar o calendario com o mes atual


                            var TR_start = '<TR>';
                            var TR_end = '</TR>';
                            var highlight_start = '<TD WIDTH="30"><TABLE CELLSPACING=0 BORDER=1 BGCOLOR=DEDEFF BORDERCOLOR=CCCCCC><TR><TD WIDTH=20><B><CENTER>';
                            var highlight_end = '</CENTER></TD></TR></TABLE></B>';
                            var TD_start = '<TD WIDTH="30"><CENTER>';
                            var TD_end = '</CENTER></TD>';

                            cal = '<TABLE BORDER=1 CELLSPACING=0 CELLPADDING=0 BORDERCOLOR=BBBBBB><TR><TD>';
                            cal += '<TABLE BORDER=0 CELLSPACING=0 CELLPADDING=2>' + TR_start;
                            cal += '<TD COLSPAN="' + DAYS_OF_WEEK + '" BGCOLOR="#F2F2F2"><CENTER><B>';
                            cal += month_of_year[month] + '   ' + year + '</B>' + TD_end + TR_end;
                            cal += TR_start;

                            for (index = 0; index < DAYS_OF_WEEK; index++) {

                                if (weekday == index)
                                    cal += TD_start + '<B>' + day_of_week[index] + '</B>' + TD_end;
                                else
                                    cal += TD_start + day_of_week[index] + TD_end;
                            }

                            cal += TD_end + TR_end;
                            cal += TR_start;

                            for (index = 0; index < Calendar.getDay(); index++)
                                cal += TD_start + '  ' + TD_end;

                            for (index = 0; index < DAYS_OF_MONTH; index++) {
                                if (Calendar.getDate() > index) {
                                    week_day = Calendar.getDay();
                                    if (week_day == 0)
                                        cal += TR_start;
                                    if (week_day != DAYS_OF_WEEK) {
                                        var day = Calendar.getDate();
                                        if (today == Calendar.getDate())
                                            cal += highlight_start + day + highlight_end + TD_end;
                                        else
                                            cal += TD_start + day + TD_end;
                                    }
                                    if (week_day == DAYS_OF_WEEK)
                                        cal += TR_end;
                                }
                                Calendar.setDate(Calendar.getDate() + 1);
                            }
                            cal += '</TD></TR></TABLE></TABLE>';

                            //  MOSTRAR CALENDARIO
                            document.write(cal);
                            //  End -->
                        </SCRIPT>
                        <!-- <nav aria-label="Previous and next months" class="wp-calendar-nav">
                            <span class="wp-calendar-nav-prev"><a href="#">« Oct</a></span>
                            <span class="pad">&nbsp;</span>
                            <span class="wp-calendar-nav-next">&nbsp;</span>
                        </nav> -->
                    </div>
                </div>
                <div class="widget-box widget_archive">
                    <h4 class="title">Arquivos</h4>
                    <ul>
                        <li><a href="#">Outubro 2008</a></li>
                        <li><a href="#">Setembro 2008</a></li>
                        <li><a href="#">Junho 2008</a></li>
                    </ul>
                </div>

                <div class="section" id="sidebar-author">
                    <div class="widget Text" data-version="1" id="Text1">
                        <h2 class="title">
                            <span>Sobre o autor</span>
                        </h2>
                        <div class="widget-content">
                            <div class="widget-content">
                                <center>
                                    <div class="photo-profile">
                                        <img alt="Avatar do/da autor(a)" class="image wp-image-139  attachment-medium size-medium" height="300" sizes="(max-width: 300px) 100vw, 300px" src="{{user.Photo}}">
                                        <br>
                                    </div>
                                    <br>
                                    <br>
                                    <h2>
                                        <span>
                                                <span>{{Post.Author}}</span>
                                        </span>
                                    </h2>
                                    <p>"{{user.Biografy}}"</p>
                                </center>
                                <br>
                            </div>
                        </div>
                        <div class="clear">
                        </div>
                    </div>

                </div>

            </div>

        </div>

    </div>
</div>

{% endblock %}

Meu_Blog/Blog/templates/sobre.html
{% extends 'base.html' %}

{% block head_title %} Sobre {% endblock %}

{% block content %}

    <div id="content" class="container content">

        <div class="row">

            <div class="col-md-12 full-width">

                <div class="row">

                    <div class="post-2 page type-page status-publish hentry post-container col-md-12">

                        <div class="post-article post-details page-details-4  ">

                            <h1 class="title">Sobre</h1>
                            <div class="line"></div>
                            <p>
                                This is an example of a WordPress page, you could edit this to put information about
                                yourself or your site so readers know where you are coming from. You can create as many
                                pages like this one or sub-pages as you like and manage all of your content inside
                                of WordPress.
                            </p>

                            <div class="clear"></div>

                            <div class="contact-form">

                                <div id="respond" class="comment-respond">
                                    <h3 id="reply-title" class="comment-reply-title">
                                        Leave a Reply
                                        <small>
                                            <a rel="nofollow" id="cancel-comment-reply-link" href="/suevafree/?page_id=2#respond"style="display:none;">
                                                Cancel reply
                                            </a>
                                        </small>
                                    </h3>
                                    <p class="must-log-in">You must be 
                                        <a href="https://wp-themes.com/wp/wp-login.php?redirect_to=https%3A%2F%2Fwp-themes.com%2Fsuevafree%2F%3Fpage_id%3D2">
                                            logged in
                                        </a> 
                                        to post a comment.
                                    </p>
                                </div>
                                <!-- #respond -->

                                <div class="clear"></div>

                            </div>
                        </div>

                    </div>

                </div>

            </div>

        </div>

    </div>
{% endblock %}